### ISSUE TITLE
Adding custom characters

### ISSUE THREAD

**Issue by dawinaj** [bradkeifer/esp32-HD44780#4]
Hello!
First of all, it's great to finally find a library that is not completely hardcoded!
Is there a way to write custom characters to the CGRAM? I couldn't find it in the source. Or maybe is it impossible with the I2C driver?

**Comment by bradkeifer** [comment]
Hi @herhor67 
The library does not currently support writing custom characters to the CGRAM, but it would be a great enhancement to make. I don't expect there to be any I2C driver issues to overcome, it's just a matter of writing and testing the code. Unfortunately, I do not have much time at the moment to add this enhancement, however, please feel free to have a go at it yourself and contribute to the library.

**Comment by dawinaj** [comment]
Very well. When I will have some free time, I may try to create such function.

**Comment by malachib** [comment]
@herhor67 I was eyeing this as well and could definitely use it.

**Comment by dawinaj** [comment]
I got the display today, so in the nearest future I should work on it. Will you be making a pull request with the recent changes on your dev branch @malachib ?

**Comment by malachib** [comment]
@herhor67 The PR just got merged.  It limits itself to shuffling .h files around though, no CGRAM work planned on my side.

I can comment though when I researched CGRAM usage there was no specific impediment to doing so with the existing I2C driver, presuming no additional mystery-timing concerns arise

**Comment by dawinaj** [comment]
> The PR just got merged. It limits itself to shuffling .h files around though, no CGRAM work planned on my side.

Of course, I understand. I am not really experienced with neither git nor github, so I'm not sure how all that works, and I wanted to make sure there won't be any issues with parallel changes.
Sorry for bothering you, but could you explain a bit how you download, and then update & PR the repo? I've done git in VS (and still had quite a trouble), but not in VSCode...
Well, this will probably be a single function, so I could just post the code somewhere, but I'd like to do it the "proper" way.

**Comment by malachib** [comment]
@herhor67 I'm happy to offer what help I can.

In my experience, getting to know "git bash" and "git gui" is well worth the investment.  I've used the vscode git integration and it actually is very good - but I only use it for merging because it's more productive (for me) to use the prior two.

There's also no getting around that git is more complicated than some other source control systems.  I'm reminded of Albert Einstein's quote "Make it as simple as possible, and no simpler".  That's GIT with source control.  It's not easy, but that's the nature of the beast.  Remember, Linus T himself invented it!

All that said, some basic advice:

* First fork your own copy, then I suggest branching a dev branch (i.e. call it `dev/cgram` or similar)
* When choosing what branch to create your `dev/cgram` from, I recommend sticking on the stablest branch possible.  For a very small repo like this one, the main branch will do just fine.
* Do all your work on your `dev/cgram` branch.  Even if new updates come, stick on your branch.

When the time comes, all your work will be neatly segregated on aforementioned branch.  The bits and pieces of a PR will sort themselves out in context of that.

**Comment by dawinaj** [comment]
Alright, I think I got that. Forked the repo and created a branch, fetched the files and can edit them.
However, I also updated the IDF to v5 and it's giving me trouble 😬 What steps are needed to build the lcd example? Or do I need to copy the example into another dir and then build?
Edit: I think I got it, even though VSC complains about missing headers, it builds just fine.

**Comment by malachib** [comment]
Good work 👍 VSC _loves_ to complain about missing headers.  Nothing to worry about!

**Comment by dawinaj** [comment]
I also found that doing backlight on/off (not sure if in certain order, or certain timing or what) is messing with the display, i.e. text was being shifted, the screen did not want to clear or home (only every second loop, like wtf even is this). However I made a function that implements the "noop" in other way than setting the cursor to current position, and it seems to be working for now.
I feel like the LCD driver needs another complete rewrite, eh...

**Comment by bradkeifer** [comment]
@herhor67 - given the work you've just completed, do you see that this issue can now be closed?

**Comment by malachib** [comment]
The main improvement this thing seems to want is more precision and less blocking when it comes to the "mystery timing"
Your churn makes me sad :(
Your cgram feature add makes me happy :)

**Comment by dawinaj** [comment]
Yeah, when I was testing it, I reduced the "mystery data clock-in timing" from 1000us to 500us and it still worked fine, though not with 100us. This is weird, I cant see something like that in the original arduino library.
Though there are many issues reported with both the original and the fork, especially with ESPs, so maybe the trashduino is so slow that it doesnt require additional timing :v

**Comment by malachib** [comment]
@herhor67 I can see we are having a similar thought process here.  I speculate the underlying I2C controller(s) (because they aren't all exactly the same, right...) have different responsiveness given different conditions.  We can be pretty sure they aren't putting an FPGA out there, after all :smile:

It occurs to me, saying that, that a compile-time tunable timing might be interesting (sorta like an overclock BIOS tuner).  I also (separately) think that making the delays a bit more async would be helpful too - without necessarily going into multitasking.  

Both avenues are non trivial, but I can have fun talking with you about it at least :smile:

**Comment by dawinaj** [comment]
First of all, it would be great to have an expander which does all 16 (or rather, 12) inputs. But it is what it is.
Im not sure what you mean by `BIOS OC tuner`, I think that we should have a runtime-tunable delays (though how can it tune itself if we have no feedback from the controller, or which *maybe* could be done by reading the busy flag from the controller and checking if it responds at all...).
I also don't quite get it, what you mean (both implementation and idea) by async delays.

**Comment by bradkeifer** [comment]
I really like the idea of runtime-tunable delays, and making them async. However, I think to go async will mean going multitasking, which is not a bad thing at all. I also suspect we are starting to talk about some serious development & testing time to do either or both of these things. Do either of you have good hardware analysis equipment to be watching what's happening on the I2C bus? I don't.

I also wonder about the value of doing these types of enhancements. It strikes me that the HD44780 is quite an old generation display and do you think there would be many people seeking to use it in an esp32 solution as an alternative to more modern displays?

**Comment by malachib** [comment]
@herhor67 BIOS OC tuner I mean an analogy to people who like to overclock their PCs via the BIOS.  Basically runtime-tunable delays, though I'd motion for compile-time tunable because I doubt you'd want to ever adjust it once the firmware was burned.

@bradkeifer is correct in your thinking of async, though I would (in theory) steer towards ISR and/or DMA because the timings are shorter than what the RTOS generally works with.  It is absolutely true though that that is a serious engineering effort to take it that far.  At this point, I'm just dreaming out loud :) 

One less beefy but potential optimization is to do the delays BEFORE the operation rather than after them.  You could then calculate (and often skip) how much delay to do since often by the time you reach that code the delay is already reached.

It is really unproven whether any of this would truly make a sizeable improvement to the experience for the programmer or the user.  I also agree with the sentiment that there may be limited overall value due to this being such an old part.  But I love hocking these ideas around!

**Comment by dawinaj** [comment]
@bradkeifer The advantage of old things is that they are pretty cheap :P I got a big-ass 20x4 LCD with driver for at least half the price of the smallest graphical displays that dont even have a breakout of the tape connector...
